[project]
name = "scikit-fem-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cudaskfem",
    "scikit-fem",
    "matplotlib",
]

[tool.uv.sources]
cudaskfem = { path = "../cuda-scikit-fem" }
scikit-fem = { path = "../scikit-fem" }

    